### ISSUE TITLE
Interactions / Hire by Microsoft

### ISSUE THREAD

**Issue by vbfox** [Krzysztof-Cieslak/AMA#1]
Did they ever evoke the possibility of hiring you or having you as an external contractor to work on F# tooling or vscode?

Or more generally what are your interactions with them ?

**Comment by Krzysztof-Cieslak** [comment]
> Did they ever evoke the possibility of hiring you or having you as an external contractor to work on F# tooling or vscode?

I'd love to work on VSCode Team (especially if I could use a bit of the time to make Ionide better).  I believe it's really good product (even if it's using TypeScript ;) ), I agree with design philosophy, and I think it's one of the best examples of OSS project done by huge corporation I've seen.

Unfortunately, the last time there was open position on VSCode Team (or maybe it's still open, haven't paid too much attention to it) it required relocation to Redmond, which is no-go for me at the moment.

> Or more generally what are your interactions with them ?

I always have had really good interactions with VF# and VSCode Team. I also know and have really good relationships with people around different Teams.
My usual criticisms of MSFT are targeted at either particular Teams which clearly don't understand OSS / Community (like NuGet Team)  and general "company culture" of ignoring OSS/Community/F# (which is slowly changing, but is still noticeable, and I don't think that pretending that problem doesn't exist is not helping anyone)
