### ISSUE TITLE
What are your favorite landscapes? (for photography)

### ISSUE THREAD

**Issue by MangelMaxime** [Krzysztof-Cieslak/AMA#12]
Let's try something less technical. After all it's one of your passion :)

**Comment by Krzysztof-Cieslak** [comment]
I don;t think I have favorite landscape for photography, I have couple of favorite views in Polish mountains... but they are not necessary best views for landscape photography.

Also, even though lot of my photos on 500px are landscapes, I don't feel like landscape photographer - most of them are created as a "side effect" of hiking, while landscape photography is about finding stunning view, patiently waiting for good light, going to the place on sunrise or sunset and  I almost never do it.
