### ISSUE TITLE
Plans with Lambda Factory

### ISSUE THREAD

**Issue by ChrSteinert** [Krzysztof-Cieslak/AMA#13]
Do you have some plans for the future with your (?) company Lambda Factory, that you would like to share? Internationalization, Growth, Sell out?

**Comment by Krzysztof-Cieslak** [comment]
I don't have any specific plans, I guess growth - both in terms of rates I charge, and maybe hiring someone if there would be such situation on the market that would allow it, Personally I'd want to move bit more into training market - at the moment I mostly do consulting/ developing
