### ISSUE TITLE
If you won the lottery, what would you do?

### ISSUE THREAD

**Issue by AnthonyLloyd** [Krzysztof-Cieslak/AMA#16]

**Comment by Krzysztof-Cieslak** [comment]
It really depends on how much would it be ;)

But some random shortlist of things I'd probably do:
 * Get apartment in some cool place like Barcelona, or house on Bahamas or somewhere like that ;)
 * Travel a lot - hiking + photography trips
 * Invest into my company 
 * Try to support F# OSS projects 
 * Try to support diversity in tech movements
