### ISSUE TITLE
Clojure / Spec

### ISSUE THREAD

**Issue by gchiaramonte** [Krzysztof-Cieslak/AMA#19]
What are your thoughts on Clojure now that Spec is available for defining type constraints (rules)? Given the tooling for Clojure is excellent and Leiningen makes working with projects very easy, what holds you back from working in Clojure? Seems to me the JVM is light years ahead of .net core, so I'm curious why you persist on .net. Thanks.

**Comment by Krzysztof-Cieslak** [comment]
I don't think I can give good answer for this one. Last time I've played with Clojure Spec was not really something advertised or popular so I haven't tried it at all. In principle I like an idea... but adding typing to the dynamic language is often problematic and existing implementation I know are rather underwhelming ( JS' Flow, Elixir typespec).

Also... LISPs are just different, I've never got comfortable with them ( that may be my problem, and not spending enough of time on it).

Regarding JVM being superior - yeah, maybe . But I don't like any of popular JVM languages.
