### ISSUE TITLE
Ionide for Enterprise?

### ISSUE THREAD

**Issue by cartermp** [Krzysztof-Cieslak/AMA#20]
What would it take?

**Comment by Krzysztof-Cieslak** [comment]
Adding [zip of death](https://en.wikipedia.org/wiki/Zip_bomb) to the installer to make Ionide use more space on disk and make it slower. ;)

--- 

How would you define it? What features should it have?

* We have rich set of language features (+/- the same set like all IDEs with F# support - VS, XS, and Rider)
* We have debugger (with some limitations.... but those should become less and less important beacuse people will move to new `fsproj`s and debugger works with those on all platforms, for both full framework and .Net Core)
* We've recently added project explorer which basically has same functionality as VS one. `Sln` support is not there yet, but we're close - there is WIP PR for it

Features we don't have:
* Good test runner - Expecto integration is super simple. VSCode doesn't have at the moment API for test explorer... it could be added with tree explorer API, tho. 
* Profiling tools - I've played with adding integration with JetBrains' dotTrace, it seemed to be working fine, I could create some nice visualizations using ContentProvider API... But it was working only on Windows, and I'm bit reluctunt to include features that will work on one OS only.
* UML thingy... uh, nope, thx.

And we even have features like CodeLens which are only in Enterprise version of VS ;)
