### ISSUE TITLE
Most sorely missed pieces in F# ecosystem?

### ISSUE THREAD

**Issue by isaksky** [Krzysztof-Cieslak/AMA#21]
What do you think are the most important missing pieces in the F# ecosystem? Limit to web, if you prefer.

**Comment by Krzysztof-Cieslak** [comment]
In the web - powerful "end-to-end" framework focused on developer experience (scaffolding, out-of-the box conventions, integration with tooling and other libraries) like Elixir's Phoenix. Freya and Suave are great but are lower-level in comparison to Phoenix and nowhere near as polished. 

Generally.... the list is long, and depends on the point of view on some of the ecosystem issues ;)
