### ISSUE TITLE
How do you convince to switch to F# ?

### ISSUE THREAD

**Issue by AntoineGa** [Krzysztof-Cieslak/AMA#22]
Hi,

I'm working in a mainly C# environment, and thus i'm using FAKE or Paket to solve actual issues, people are afraid to learn or do more F#.

Do you have arguments to help me convince them to switch to F# ?

Thanks !

**Comment by Krzysztof-Cieslak** [comment]
I don't really know, usually I work with companies and teams that have already decided to use F# and need someone experienced in language and its patterns to help with projects, introduce those patterns, mentor/train people a bit.

In general, I believe that introducing F# in places that doesn't have too much business value (so there is no risk) but are something that every project needs is good idea. So FAKE for build scripts, unit testing (Expecto / FsUnit / Unquote) , UI testing (Canopy). The next step would be writing some green field module / application that is not critical to the system with F# and showing that there are no problems with it on production etc.
