### ISSUE TITLE
Relational vs. Document vs Graph

### ISSUE THREAD

**Issue by jonathanfishbein1** [Krzysztof-Cieslak/AMA#26]
Any thoughts on these data schemes from the perspective of developers that value the qualities a functional, statically typed language?

More specifically what are you're thoughts about the azure/Microsoft offerings CosmosDb, and Graph Engine

**Comment by Krzysztof-Cieslak** [comment]
I don't think I'm expert on this topic.... so all I can say - I've been using both Relational and Document data bases with F# and I've been happy with both kinds. I wouldn't say choice of either has anything to do with the programming language paradigm that is used, but rather with different requirements of the application.
