### ISSUE TITLE
How happy are you with the current state of the art in F# projects/build/packaging ?

### ISSUE THREAD

**Issue by ccozianu** [Krzysztof-Cieslak/AMA#28]
In particular, are you happy with what Ionide generates for a new console app, for example ?

Cheers,
Costin

**Comment by Krzysztof-Cieslak** [comment]
In comparison to some modern ecosystems? I'm not happy at all, I think it's complex, error prone, and with steep learning curve.

But FAKE, Parket and Forge are still best choices we have on .Net, and situation is much better than in most .Net projects - things are cross platform, buildable directly from the repo, there is single point of entry for the build, it's easy to add more complex process with FAKE.
