### ISSUE TITLE
F# and .NET Core 2.0

### ISSUE THREAD

**Issue by mgaff** [Krzysztof-Cieslak/AMA#29]
Hey would you recommend to someone starting out in F# to begin building projects in .NET Core 2.0 or would you advise him/her to build on top of the more established systems like Mono, I'm on macOS, to avoid potential pitfalls with the new infrastructure?

**Comment by Krzysztof-Cieslak** [comment]
Mono still is required for developer machines, all tools require it. Also .Net Core 2.0 is still in flux - it's been just few weeks after the release.

But in general, as a runtime .Net Core seems much more stable and faster than mono... so I'd go with it.
