### ISSUE TITLE
What is still missing for you in F#

### ISSUE THREAD

**Issue by dadhi** [Krzysztof-Cieslak/AMA#3]
What would you love to add, change, remove in F# ?

**Comment by Krzysztof-Cieslak** [comment]
I would love to have Dependent Types... and Higher Sorted Kinds ;)

And now serious answer - I don't think language features are problem at all, I'm pretty happy with it. I feel the weakness of F# is ecosystem around it, not language itself.

**Comment by dadhi** [comment]
What is the problem with ecosystem?
