### ISSUE TITLE
Functional types in REST services

### ISSUE THREAD

**Issue by whitebear-gh** [Krzysztof-Cieslak/AMA#30]
Hi,

What do you think about using functional types (like discriminated unions) as models in REST endpoints? Especially in microservices infrastructure where communication may happen between many technologies and representing functional types in OO world is not trivial. 
Maybe it's a better choice to write REST in C# (or only with POCO classes) and map them later to business domain objects?

**Comment by Krzysztof-Cieslak** [comment]
I've been quite successful with using F# types (records, DUs - both multiple case, and single case just for wrapping primitive types) and custom serialization for "REST" APIs. For the input - we're able to validate (at least partially) data automatically for each request, for output - we are sure that we shape output as we want. In both cases the advantage is that we don't need to create any ideational DTO types ( what is usually done for such kind of the problems)
