### ISSUE TITLE
Getting startet building a Visual Studio Code extension in FSharp with reference to interop library

### ISSUE THREAD

**Issue by lukasimir** [Krzysztof-Cieslak/AMA#31]
Hi, I'd like to write a VS Code extension to provide tooling for development in a specific simulation software that provides a .NET API. It should

- do syntax highlighting
- provide commands to push/pull code to/from the simulation
- (later) do more sophisticated interactions with the simulation

Ideally I'd like to do that in FSharp. You seem to be an expert on this. How to I get started and what are the design-questions I need to ask myself first? Thanks!

**Comment by lukasimir** [comment]
OK, I found your tutorial and the example and it works =) Thanks for that.

http://kcieslak.io/Creating-VS-Code-plugins-with-F-and-Fable
https://github.com/Krzysztof-Cieslak/fable-vscode-demo

Has anything fundamentally changed since then or is that still the recommended starting point?

The next thing is that the API of that simulation software is actually a COM interop DLL that I wrapped into a VB.NET library. Can one of them be consumed from within the vscode-fable extension? My first attempt simply referencing the COM DLL didn't work. Thanks!

**Comment by Krzysztof-Cieslak** [comment]
I think looking at Ionide repo is best way to get started, there is even PR updating it to Fable 1.X, so things should be more up to date than my outdated sample. However, I'll probably soon publish some materials about creating extensions since I'm doing talk and workshop about it on FableConf.

For communicating with any external system ( no matter if it's something like COM or just simple .Net lib) you need to create wrapper that will communicate with protocol that can be easily used from JavaScript (node), for example standard I/O or HTTP. We do exactly the same to communicate with FSharpCompilerServices using FsAutocomplete project.

**Comment by lukasimir** [comment]
I posted the question about referencing the COM interop library also here:
https://stackoverflow.com/questions/46031752/how-to-reference-a-com-type-library-interop-in-a-vs-code-extension

In the meantime, I realised I need to use one of these two node libraries:

- https://www.npmjs.com/package/win32ole
- https://www.npmjs.com/package/winax

Unfortunately, I couldn't get win32ole installed (some compilation errors kept occurring). Installing winax was straightforward though. But now I don't understand how to consume it from F#/Fable. I found this

- http://fable.io/docs/interacting.html

but nothing I try with importAll, importDefault or createNew seems to do the job. Any help would be just great. Thanks!

Actually, I tried to use winax in a clean plain VS Code extension in JS (not F#) and that doesn't seem to work either. So maybe COM interop just doesn't work in VS Code? Can it be?

**Comment by lukasimir** [comment]
Oh, I just saw your comment now. Thanks anyway =)

Yes, I will have to write that wrapper, even though I don't understand it well enough yet. Does it mean the wrapper needs to be a command line tool for example witten in F#? Or would for example Edge.js be a way to go?
https://www.npmjs.com/package/edge

Thanks again :)

**Comment by Krzysztof-Cieslak** [comment]
VSCode extensions are run as normal node.JS processes so anything that works in node should work just fine. However winax docs mention recompiling if library is used in Electron app, maybe same is required in this case

**Comment by lukasimir** [comment]
Just to complete the thread: I managed to get Winax do the thing, see https://stackoverflow.com/a/46112063/6454590

To be honest, looking at a large (and awesome) extension like Ionide to get started is asked a bit much ;/ But, apart from your blog post linked above, these two articles helped me a lot to get started:

- http://fable.io/docs/interacting.html
- https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f

Thanks again for your help and thanks a lot for your work on Ionide etc.
