### ISSUE TITLE
Github vs Gitlab

### ISSUE THREAD

**Issue by piaste** [Krzysztof-Cieslak/AMA#32]
Hi Krysztof,

I noticed that your open-source work is mirrored on both Github and Gitlab (possibly others?).

When do you use either/both site? Do you have a preference for or against each one?

**Comment by Krzysztof-Cieslak** [comment]
I don't really "mirror" things just host some stuff on GitLab. I prefer GitLab from technical point of view - better way of handling CI, publishing documentation pages, better control over access privileges.

However GitHub is place where community is, and adding more problems for contributors than needed is just wrong from community building point of view. So for OSS projects I'd suggest GitHub.
