### ISSUE TITLE
What is your story?

### ISSUE THREAD

**Issue by nikolenkoanton92** [Krzysztof-Cieslak/AMA#36]
Hi,

How you become so good in programming and Do you have tips or advises? 

Thanks,
Anton

**Comment by Krzysztof-Cieslak** [comment]
First of all, I wouldn't say I'm "so good in programming". I have quite a lot of niche knowledge about F# tooling and bit less about Developer Experience and I've been vocal about this topics. Being vocal <> being really good ;-)

I guess the story is really ordinary - I've started with programming in high school, then I've been studying for a while, and freelancing at the same time. Then I've dropped out and started to work full time (C# + TS).  In 2015 I've started doing F# OSS in free time (and back then I had absolutely no idea about editor tooling and my F# was really bad) and slowly step by step, feature by feature I improved products, my understanding of the user base, cooperation with the community, and my technical skills. The relative success of Ionide opened me a door to working with some international companies and starting my own company.   

The general tips for new people / junior developers I'd have are:

* Attend conferences, talk with people there, don't be afraid to ask questions or chat with the speaker after the talk. Especially for topics/technologies, you don't know a lot about - widening horizon, being open-minded, getting new ideas from others is super important.

* Try to learn a couple of totally different programming languages. If you just know some C-family languages, learn type-FP ML-family language, LISP-family language, maybe some Prolog for logic programming.  Different paradigms often achieve different solutions for same problems, and even if you won't ever program in any of the less mainstream languages it will make you a better developer. 

* Be patient. You can have the best education, you can have amazing talent but in the end, the most valuable thing in software development is the experience. And you will need to learn from your own mistakes. Look for the mentors that will make this learning process smoother - maybe senior developers in the company, maybe someone from the online community.

* Be a part of your local software development community. Life is not only happening online but also offline, and the network you build offline is usually more reliable than random people you know from Twitter. 

* Be aware of burn out. New people are often super enthusiastic and want to learn everything, do everything, try everything and they end up putting way too much effort and time into software development. I've heard some stories about people having set up plans like: "8h work + 2h watching online courses + 2h practising some coding katas + doing stuff for online community etc". I think the life-"software development" balance is super important, everything you gained by such regime and putting so much effort will be lost when you just burn out, stop doing anything or get depressed.
