### ISSUE TITLE
WPF ObservableCollection |> F#

### ISSUE THREAD

**Issue by TonyHenrique** [Krzysztof-Cieslak/AMA#37]
Hi, I use a lot WPF(XAML DataBind) + ObservableCollection + MVVM

How can I do this using F#, on a functional way?

How to update the View automatically, using the F# immutable way of doing things?

Can you do a blog posting explaining how to use F# with XAML DataBind (WPF or Xamarin Forms), for example, a Customer, a Order and OrderLines ?

**Comment by Krzysztof-Cieslak** [comment]
I haven't done any WPF in ages so don't know a lot about it.

There are the couple of F# libraries that makes writing WPF applications in more F# idiomatic way possible. Main ones are:
* https://github.com/fsprojects/FSharp.ViewModule - library providing useful (from F# point of view) helpers for writing "classical" MVVM applications
* http://reedcopsey.github.io/Gjallarhorn/ - it's a library that provides a mechanism for managing state and building applications using observable, reactive applications with a unidirectional data flow.
* https://github.com/Prolucid/Elmish.WPF - implementation of ModelViewUpdate (so-called "Elmish") architecture.
