### ISSUE TITLE
How to use F# Type Provider to consume an API having Swagger on ASP.Net Core 2 WebAPI? 

### ISSUE THREAD

**Issue by TonyHenrique** [Krzysztof-Cieslak/AMA#38]
How to use F# Type Provider to consume an API having Swagger on ASP.Net Core 2 WebAPI? 

Is this possible? It would be nice to have a strongly typed Client generated automatically for consuming WebAPI operations on F#

https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger
http://www.talkingdotnet.com/add-swagger-to-asp-net-core-web-api/

**Comment by Krzysztof-Cieslak** [comment]
There already exists Swagger Type Provider that generates type safe client for given swagger file. You can find it here - http://fsprojects.github.io/SwaggerProvider/
