### ISSUE TITLE
Ionide docs

### ISSUE THREAD

**Issue by jackfoxy** [Krzysztof-Cieslak/AMA#41]
Ionide docs are very incomplete, with headings for the most interesting/useful parts 

Project managment (sic) management
Debugging 
Testing 
Paket integration 
FAKE integration 
Reference

Will these sections ever be complete?

**Comment by Krzysztof-Cieslak** [comment]
PRs are welcomed.

**Comment by forki** [comment]
@jackfoxy  ionide docs need community efforts - not chris alone!

**Comment by jackfoxy** [comment]
@forki if I could write the docs, I wouldn't be asking.
