### ISSUE TITLE
At which conferences will you be presenting in 2018?

### ISSUE THREAD

**Issue by aggieben** [Krzysztof-Cieslak/AMA#42]
I'm pretty hungry to hear quality presentations from experienced F# developers, particularly those doing OSS.  Have you got any conferences scheduled that you're excited about?

**Comment by Krzysztof-Cieslak** [comment]
I'm already confirmed on:
* [OSCon Portland](https://conferences.oreilly.com/oscon/oscon-or), 16th-19th July - 3h tutorial about Fable
* [OpenF#](http://www.openfsharp.org/), 27th-28th Spetember, San Francisco - workshop about F# web development
 
I hope to be speaking at:
 * FableConf - about something, maybe OSS
* Remmidemi - about something, maybe OSS
* Not-yet-announced FP conf in Prague - about something, maybe OSS
 
And some other confs I'd love to speak on but I need to go through normal CFP process, I guess:
* .Net Fringe (if it happens this year)
* nCrafts Paris
* BuildStuff Lithuania 

And I'm always open if sometimes want to invite me to any other conferences, but I do require (mostly) covering travel and accommodation costs.
