### ISSUE TITLE
Would you want to move Fornax to GitHub?

### ISSUE THREAD

**Issue by WalternativE** [Krzysztof-Cieslak/AMA#45]
I know that Fornax did not gain the traction you originally anticipated. I personally like it a lot - it does the thing it should do in a way I can easily comprehend (and I don't have to use Ruby which is a pain to use on Windows).
Do you think moving the project to GitHub would maybe increase the projects discoverability and would incline more people to spend time on the project?

**Comment by Krzysztof-Cieslak** [comment]
Yes, I think it may be good idea. Will try to find some free time to do it
