### ISSUE TITLE
Ionide, 100€ a year?

### ISSUE THREAD

**Issue by whitetigle** [Krzysztof-Cieslak/AMA#46]
Dear K,
after playing with Rider, my present fear, which I think many of us share at the moment is that ionide may disappear would you decide to relocate in some remote Carribean heavens and then we would certainly understand what it is to use an Atari after having proudly owned an Amiga. (that was the Troll part from the old gamer I am).

**I would pay for Ionide. I think many of us would do the same.**

GitKraken is free for Open Source and you have to pay if you're using it for commercial projects.
I think that's fair. So like GitKraken, I would be ok to pay for some ionide pro version, which could be an oss version slightly different (maybe?)

The goal would be to fund the development in the long term. Fund you and maybe a team around this project. 

I'm sure this has been discussed zounds of times. However, I have absolutely no idea what you think about this idea. You may have already done your math. And maybe it cannot be sustainable.

To be frank, I have absolutely no idea about how many people use ionide. Are we talking about 100 people? 1000? 

So. I love what you do and I whish to thank you for all this energy you spend making great tools for mere mortals like me. 

So since nowadays I can't find time to help you by contributing on the codebase, I would be glad to help you this way.

Thanks for your answer!

**Comment by Krzysztof-Cieslak** [comment]
OK, so there are couple of question here.

First of all, relocating to some remote Caribbean heaven sounds like good plan :D 

Secondly, how many people are using Ionide. I don't have any exact numbers - VSCode marketplace just gives total download count which is not really super useful. But by tracking change of number of downloads I can estimate number of users to somewhere between 4000 and 6000 installations. Which doesn't give any exact numbers of users, nor doesn't tell us anything about how many people are using it regularly, or as main tool  

The question of funding is difficult one - there are many potential strategies for monetizing and sustaining OSS projects. Each has their own advantages, and disadvantages and it's probably topic for blog post (or couple), not for short answer ;) But couple of my opinions:
* I don't want Ionide to be a product (i.e selling it, providing dual licensing, etc)
* I don't believe into crowd-sourcing as a way to build long term sustainability. I think it's putting "pressure" on wrong parts of userbase - individual users who are already engaged with community. 
* I think that selling something around Ionide, maybe additional extension adding some new features (for example better test experience - test explorer, code lenses for tests, continues runner etc) could be an option I may want to investigate. However I'm not sure how viable it would be given scale of F# and Ionide userbase
* I think that "build consulting around OSS" is really reasonable way of sustaining OSS, but clearly Ionide is not good use case for that, maybe Saturn will show different story
* I believe that corporate sponsoring is best way of sustaining OSS which is win-win scenario for both sides, but it looks like companies using F# are not really interested in that unfortunately.

In general all this stuff is rather complex, and is connected to OSS model of development, what role maintainers should have in the projects, and more... I'm planning to do some blog posts about it, and hopefully do some talks on this topic, too :)

**Comment by whitetigle** [comment]
Excellent! 
Thanks @Krzysztof-Cieslak for this detailed answer. 
Can't wait to read your blog posts now ;)
