### ISSUE TITLE
Any chance PureScript (or anything else) is in your future?

### ISSUE THREAD

**Issue by daxfohl** [Krzysztof-Cieslak/AMA#5]
You've made major contributions to Elm and F#.  Elm is kind of a limited browser-only player (last I checked), and F# suffers from MS/OSS dichotomy.  Haskell is somewhat over-saturated.  OCaml seems IDE-averse.  But PureScript seems perhaps ideal and ripe.  Have you considered any work in that direction?  Or are there other languages that you're considering adopting?

**Comment by Krzysztof-Cieslak** [comment]
This question can be answered from multiple point of views ;)

1. For "Fun" - Yes, PureScript is one of the languages I'd like to check out, I enjoy playing with different languages, I like to play with Haskell and Idris as a "mental exercise", so yeah, PureScript sounds fun. 
2. For OSS - I don't know, if the language is fun enough then why not.
3. For work - Probably not, from business perspective I believe more into using "pragmatic" FP languages like F#, Elm, Elixir. But who knows what will future bring ;)
