### ISSUE TITLE
Would you consider a one-time-purchase model for Saturn?

### ISSUE THREAD

**Issue by aggieben** [Krzysztof-Cieslak/AMA#51]
I would be very interested in using (and paying for) Saturn, but the sticking point for me is that it would be primarily for side projects, and therefore would have to come out of my monthly "blow money" (money in my family budget that I can spend on whatever), which is quite limited, so a monthly subscription is a big deal for something that isn't an essential-for-my-job kind of tool.  Have you considered offering a one-time purchase model for Saturn?

**Comment by Krzysztof-Cieslak** [comment]
No, I haven't really considered one-time purchase model. I'm mostly bit worried about how it would look like in terms of pricing. 

However we provide alternative to the monthly subscription which is yearly subscription (which is also cheaper than 12 monthly payments). Maybe this one could work for you better?

**Comment by MangelMaxime** [comment]
I am confused, are we speaking of Neptune here or Saturn ? 

Because I know the first one have a subscription model but isn't Saturn a free OSS project ?

**Comment by Krzysztof-Cieslak** [comment]
Yeah, I assumed it's question about Neptune ;-)

**Comment by MangelMaxime** [comment]
Ok :)

Perhaps we can rename the question, just to avoid any bad side effect etc. :)
