### ISSUE TITLE
Time Management

### ISSUE THREAD

**Issue by ChrSteinert** [Krzysztof-Cieslak/AMA#7]
Seeing how much stuff is going on at your end I really wonder: where do you get all the time for that?
How much time do you invest in effective OSS contribution, how to you manage to still stay "alive" while seemingly not sleeping or having a day to day job?

**Comment by Krzysztof-Cieslak** [comment]
I think contributing to OSS is really similar to reading lot of books, in the context of time management. If you ask anyone reading a lot, he'll say it's not about reading fast, or sitting from time to time and reading whole book at once - it's about doing it regularly, every day, even some small amount of time like 30 minutes daily.
So similarly, I think it's mostly about spending this 1 hour daily, but every day - my WakaTime tells me that I've spent 6 hours in last 7 days on my OSS projects, no more than 2 hours daily.  

Also, I'm lucky enough to have ability to be rather flexible about the work hours in my job, and relatively flexible about the how much I work every day.

**Comment by ChrSteinert** [comment]
Excellent answer. Hope it servers as motivation for a lot of ppl, just like it did for me - Thanks a lot!
